# Generated by Django 4.2.1 on 2023-06-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_group', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2023-04-05', verbose_name='Data da Falta'),
            preserve_default=False,
        ),
    ]
