# Generated by Django 4.2.1 on 2023-06-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_group', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota'),
        ),
    ]
