# Generated by Django 4.2.1 on 2023-06-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_group', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='Nome')),
                ('contact_number', models.CharField(max_length=32, verbose_name='Telefone')),
                ('phone_number', models.CharField(max_length=32, verbose_name='Celular')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('street', models.CharField(max_length=512, verbose_name='Logradouro/Rua')),
                ('number', models.CharField(max_length=16, verbose_name='Número')),
                ('extra', models.CharField(max_length=64, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=64, verbose_name='Bairro')),
                ('city', models.CharField(max_length=256, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('groups', models.ManyToManyField(through='student_group.StudentGroup', to='groups.group', verbose_name='Estado')),
            ],
        ),
    ]
