# Generated by Django 4.2.1 on 2023-06-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('student_group', '0003_alter_studentgroup_group_alter_studentgroup_students'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(through='student_group.StudentGroup', to='groups.group', verbose_name='Turmas'),
        ),
    ]
