# Generated by Django 4.2.1 on 2023-06-01 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0002_schoolclass_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolclass',
            old_name='School_supplies',
            new_name='school_supplies',
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
