# Generated by Django 4.2.1 on 2023-06-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0003_rename_school_supplies_schoolclass_school_supplies_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolSupplies',
            new_name='SchoolSubjects',
        ),
        migrations.RenameField(
            model_name='schoolclass',
            old_name='school_supplies',
            new_name='school_subjects',
        ),
    ]
