# Generated by Django 4.2.1 on 2023-06-02 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0004_rename_schoolsupplies_schoolsubjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('complement', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('fu', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('registration', models.CharField(max_length=10, unique=True)),
                ('date_born', models.DateField()),
                ('cell_phone', models.CharField(max_length=10)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_student.adress')),
                ('school_classes', models.ManyToManyField(related_name='students', to='register_student.schoolclass')),
            ],
        ),
    ]
