# Generated by Django 4.2.1 on 2023-06-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_student', '0006_score_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.IntegerField(),
        ),
    ]
