# Generated by Django 4.2.1 on 2023-06-09 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0001_initial'),
        ('student_group', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Turma', to='groups.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estudante', to='students.student', verbose_name='Student'),
        ),
    ]
