# Generated by Django 4.2.1 on 2023-06-09 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_groups'),
        ('groups', '0001_initial'),
        ('student_group', '0003_alter_studentgroup_group_alter_studentgroup_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='groups.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='students.student', verbose_name='Student'),
        ),
    ]
