# Generated by Django 4.2.1 on 2023-06-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_group', '0004_alter_studentgroup_group_alter_studentgroup_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgroup',
            old_name='students',
            new_name='student',
        ),
    ]
