# Generated by Django 4.2.1 on 2023-06-10 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0002_alter_student_groups'),
        ('student_group', '0006_rename_group_studentgroup_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_student', to='groups.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to='students.student', verbose_name='Student'),
        ),
    ]
